### ISSUE TITLE
Error when a pydantic field is a tuple of variable length

### ISSUE THREAD

**Issue by streitl** [EricWebsmith/pydantic-2-mermaid#4]
First of all, thank you for this library, it is very useful!

I'm encountering an error when building the diagram of pydantic classes where some fields are tuples of variable size.
For instance, if I try running pydantic-2-mermaid on this class:

```
class Data(BaseModel):
    variables: tuple[Variable, ...] = Field(...)
```

I run into the following error:
```
Traceback (most recent call last):
  File "bin/pydantic-mermaid", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "lib/python3.11/site-packages/pydantic_mermaid/__main__.py", line 87, in main
    mg = MermaidGenerator(module_type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/pydantic_mermaid/mermaid_generator.py", line 12, in __init__
    self.g: MermaidGraph = PydanticParser()(module)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/pydantic_mermaid/pydantic_parser.py", line 94, in __call__
    field_type_name = _get_name(field.annotation)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/pydantic_mermaid/pydantic_parser.py", line 38, in _get_name
    sub_names = [_get_name(sub_type) for sub_type in get_args(v)]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/pydantic_mermaid/pydantic_parser.py", line 38, in <listcomp>
    sub_names = [_get_name(sub_type) for sub_type in get_args(v)]
                 ^^^^^^^^^^^^^^^^^^^
  File "lib/site-packages/pydantic_mermaid/pydantic_parser.py", line 31, in _get_name
    return v.__name__
           ^^^^^^^^^^
AttributeError: 'ellipsis' object has no attribute '__name__'. Did you mean: '__ne__'?
```

I am able to fix this by replacing the type of `variables` by `list[Variable]`, but ideally this should work with tuples as well.

**Comment by EricWebsmith** [comment]
Hi Luo, 

Thanks for the feedback. This is fixed in 0.7.1
